### ISSUE TITLE
no Ruby script found in input (LoadError)

### ISSUE THREAD

**Issue by pinny87** [attenzione/SublimeLinter-scss-lint#17]
Hi, 

`scss-lint` works for me from the command line. However, all my other Sublime linters work with the exception of this one.

 This is the output I am getting in the console:
```
SublimeLinter: scss: custom.css.scss ['/home/user/.rbenv/shims/ruby', '/home/user/.rbenv/shims/scss-lint'] 
SublimeLinter: scss output:
ruby: no Ruby script found in input (LoadError) 
```

Config details are:
 - Arch Linux
 - rbenv (0.4.0-129-g7e0e85b)
 - ruby (2.1.5)
 - Sublime Text 3 (buld 3065)
 - SublimeLinter (3.4.22+1)
 - SublimeLinter-contrib-scss-lint (1.0.3)
 - scss-lint (0.30.0)

Any suggestions?

**Comment by AndersSchmidtHansen** [comment]
I had the exact same problem. Solved it by adding these lines to my `paths` in 'SublimeLinter.sublime-settings`:

```
 "linux": [
    "~/.rbenv/shims",
    "~/.rbenv/bin",
    "~/.rbenv/plugins/ruby-build/bin"
],
```
Had to restart Sublime for it to work. Might not work for you, but since we're both on Linux (mine is ElementaryOS tho'), who knows?

Good luck, hope you get it to work!

**Comment by pinny87** [comment]
Thanks for this. Works for me.
