### ISSUE TITLE
question about .scss-lint.yml

### ISSUE THREAD

**Issue by calledT** [attenzione/SublimeLinter-scss-lint#19]
where should I place my `.scss-lint.yml` file. I put it in the root directory or sass floder of my project, but both cound't work.

**Comment by robcolburn** [comment]
Found this to be true, a restart of Sublime, and it seems to pick up the config file.

**Comment by jonnymaceachern** [comment]
@attenzione I'm on Windows and the linter is working, but it's using my `.scss_lint.yml` config. I've tried using several config templates and putting them in both my home directory (`C:/Users/Jonny`) as well as my project root. I've restarted Sublime each time to test it and haven't had it work yet.
