### ISSUE TITLE
have scss package installed

### ISSUE THREAD

**Issue by jschaftenaar** [attenzione/SublimeLinter-scss-lint#21]
I just installed scss linter and it works perfect. 

I am not sure how this is on other platforms(I am on windows) but I first needed to have the scss package installed before it would run and this took the longest for me to find out. I was identifying scss as css and had a hard time figuring this out.

You might want to include this dependency in the readme, if it is not there already.

**Comment by wayferer** [comment]
Can you link to the package you installed?

**Comment by jschaftenaar** [comment]
I installed this one https://packagecontrol.io/packages/SCSS but any scss package should do.

**Comment by wayferer** [comment]
thanks.

**Comment by attenzione** [comment]
i haven't installed this package and linter works.
