### ISSUE TITLE
Not linting .css files

### ISSUE THREAD

**Issue by himedlooff** [attenzione/SublimeLinter-scss-lint#22]
I'd like the ability to use scss-lint to lint my `.css` files through sublime text, instead of having to configure two different linters. I can't seem to get it to work though. In `.scss-lint.yml` I'm trying `scss_files: '**/*.css,**/*.scss'` and this `scss_files: '**/*.css'`. Neither work.

**Comment by himedlooff** [comment]
Also, I believe that scss-lint allows you to lint `.css` files. So it seems appropriate to allow this in SublimeLinter-scss-lint as well.

**Comment by techdragon** [comment]
This should be optional. Can we put this behind a configuration flag of some kind?

**Comment by attenzione** [comment]
I agree, that this should be optional, but enabled by default. If anyone can create patch, i would be appreciated.

**Comment by tomodwyer** [comment]
It would be great if this could be optional. I put in place a quick hack for myself and will post it here for anyone else who wants to turn the CSS linting off.

If you go to:
`Preferences -> Package Settings -> Sublime Linter -> Settings - User`

Then edit the `SublimeLinter.sublime-settings` file:

````json
            "scss": {
                "excludes": [
                	"*.css"
                ],
            }
````
