### ISSUE TITLE
Sort by property order set in PropertySortOrder

### ISSUE THREAD

**Issue by grrowl** [attenzione/SublimeLinter-scss-lint#23]
Bit of a feature request, but it would invaluable to be able to sort properties as defined in `PropertySortOrder`. At the moment I'm using [concentric](http://rhodesmill.org/brandon/2011/concentric-css/) but reading the order from the status bar then sorting by hand is extremely time consuming.

What are the changes of this being implemented? Where would be a good place to start?

**Comment by attenzione** [comment]
Linters doesn't change source files
All u need is [CSScomb](https://github.com/csscomb/sublime-csscomb)
Highly customizable
You can create macro: before running linter, run CSSComb

**Comment by grrowl** [comment]
Awesome reply, just what I'm after :+1:
