### ISSUE TITLE
ruby + gem (unnecessary) 

### ISSUE THREAD

**Issue by yairEO** [attenzione/SublimeLinter-scss-lint#24]
Why is this coupled to using RUBY and GEMS? 

it should be coupled to a simple CLI program without the need for Ruby at all. 
it makes no sense to force developers to install runy and use gems just to lint SCSS files.

**Comment by attenzione** [comment]
Linter is written on ruby, this is plugin for Sublime for scss linter.
You can try to search somethins like 'scss linter without ruby'
