### ISSUE TITLE
(more) no Ruby script found in input (LoadError)

### ISSUE THREAD

**Issue by good-idea** [attenzione/SublimeLinter-scss-lint#26]
I'm getting the same errors as reported in this issue: https://github.com/attenzione/SublimeLinter-scss-lint/issues/17
but that solution isn't working for me.

The error in the console:

```
SublimeLinter: scss: main.scss ['/usr/local/opt/rbenv/shims/ruby', '/usr/local/opt/rbenv/shims/scss-lint'] 
SublimeLinter: scss output:
ruby: no Ruby script found in input (LoadError) 
```

I'm using:
- Mac OS X 10.10
- Sublime Text 3
- Ruby 2.2.0
- latest SublimeLinter
- latest SublimeLinter-contrib-scss-lint

Added the following in my user preferences:

```
        "paths": {
            "linux": [],
            "osx": [
                "/usr/local/opt/rbenv/shims/",
                "~/.rbenv/shims",
                "~/.rbenv/bin",
                "~/.rbenv/plugins/ruby-build/bin"
            ],
            "windows": []
        },

```

I've confirmed that scss-lint is working in terminal. My other installed linter (CSS) is working as well.

**scss_lint** _is_ in `/usr/local/opt/rbenv/shims/`

Any suggestions?

**Comment by joeyhoer** [comment]
Same issue here. A possible fix? https://github.com/elstgav/SublimeLinter-slim-lint/issues/3

**Comment by joeyhoer** [comment]
Indeed, I was able to get it working by replacing `executable = 'scss-lint'` with `cmd = 'ruby -S scss-lint'` and removing the `cmd` function. I'm not sure if this is tenable for all users, but it appears to be an approach used by other SL plugin's, so it might be worth considering.

**Comment by SQbiz** [comment]
Hey @joeyhoer, could you point out where you made those changes?

**Comment by joeyhoer** [comment]
Open `~/Library/Application Support/Sublime Text 3/Installed Packages`, and find the `SublimeLinter-contrib-scss-lint.sublime-package` file. This file is simply a renamed `zip` archive. Unzip the file into a directory named `SublimeLinter-contrib-scss-lint`, and move this directory from `Installed Packages` into `Packages`. You'll find all the source files in the `SublimeLinter-contrib-scss-lint` directory. The specific changes are made in `linter.py`. No need to repack the directory at this point, assuming everything else has been configured correctly, this should now be working.

**Comment by SQbiz** [comment]
That did it, thanks @joeyhoer !

**Comment by techdragon** [comment]
Can we get a configuration flag to put back the old behaviour? 

I use rbenv on OS X and the newly merged behaviour doesn't work for me.

```
techdragon  ⓔ  techdrgn.com  ⋯  github.com  techdragon  techdrgn.com  /usr/bin/ruby -s scss-lint                                                                 master 
/usr/bin/ruby: No such file or directory -- scss-lint (LoadError)
 techdragon  ⓔ  techdrgn.com  ⋯  github.com  techdragon  techdrgn.com  scss-lint                                                                             1   master 
No SCSS files specified
````

**Comment by attenzione** [comment]
i'm using rbenv on OSX and everything working

**Comment by nickdunn** [comment]
I'm also receiving this error:

    SublimeLinter: scss activated: ['/Users/nick.dunn/.rbenv/shims/ruby'] 
    SublimeLinter: scss: _code.scss ['/Users/nick.dunn/.rbenv/shims/ruby', '-S', 'scss-lint', '--config', '/Users/nick.dunn/src/site/.scss-lint.yml'] 
    SublimeLinter: scss output:
    ruby: no Ruby script found in input (LoadError) 

* OSX 10.11
* Sublime Text 3
* Ruby 2.2.0

I have installed ruby using rvm and I'm happy that SublimeLinter is correctly discovering my ruby from my $PATH:

    SublimeLinter: computed PATH using /bin/zsh:
    /Users/nick.dunn/.rbenv/shims
    /usr/local/bin
    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /usr/local/bin
    /opt/X11/bin
    /opt/ImageMagick/bin

**Comment by nickdunn** [comment]
I've tried following the instructions to unzip the package and make the change, but ST3's console lists a load of errors if I leave it as a folder rather than a zip/package. And if I re-zip, Package Control just downloads the latest version again anyway!

Would dearly love to see a more robust fix for this soon. How can I help?

**Comment by attenzione** [comment]
SL4 automatically detects executable, everything should work
