### ISSUE TITLE
"Should match regex /BEM/" everywhere

### ISSUE THREAD

**Issue by andradei** [attenzione/SublimeLinter-scss-lint#30]
Why is my linter complaining about elements that are _default CSS tags_?

<img width="1680" alt="screen shot 2015-08-02 at 15 32 52" src="https://cloud.githubusercontent.com/assets/2653546/9028147/df3b9ee6-392b-11e5-85ea-30de36030aaf.png">

**Comment by attenzione** [comment]
https://github.com/brigade/scss-lint/issues/319
