### ISSUE TITLE
bundle_exec option no longer works

### ISSUE THREAD

**Issue by mikesherov** [attenzione/SublimeLinter-scss-lint#32]
https://github.com/attenzione/SublimeLinter-scss-lint/pull/28 removed the ability to use a bundled gem. :-/

**Comment by mikesherov** [comment]
I'd submit a patch, but wondering if there was a reason this was removed?

**Comment by attenzione** [comment]
I think this was removed due it's works only through bundle. Need solution, which will work with and without bundler.

**Comment by mikesherov** [comment]
Seems like we could support both no problem, just the previous PR didn't account for that, no?

**Comment by attenzione** [comment]
seems no

**Comment by mikesherov** [comment]
Meaning, if `bundle_exec` option is the passed, we do `bundle exec scss_lint`, and if not, we do `/usr/bin/ruby -S scss_lint`. Why doesn't that work?

**Comment by attenzione** [comment]
can you create pull request, to fix it in that way?

**Comment by attenzione** [comment]
This plugin should be used without bundler. Install scss-lint as global gem. Most of linters works same.

**Comment by mikesherov** [comment]
That's not true, especially for node, and especially not for different projects using different rules / settings.
