### ISSUE TITLE
Help required with installation

### ISSUE THREAD

**Issue by s10wen** [attenzione/SublimeLinter-scss-lint#35]
I've got `scss-lint` installed global, using ST3, when I view installed packages I can see `SublimeLinter-contrib-scss-lint`, added a `.scss-lint.yml` file, restarted ST, I've then saved a `_whatever.scss` file that I know should bring up an error but I'm not seeing anything.

Is there a step I've missed, or a way I can debug please?

I'm guessing that on saving the document, I should get some errors up somewhere? but I'm not sure where I'd should be seeing these errors.

**Comment by attenzione** [comment]
Complete guide is here: http://www.sublimelinter.com/en/latest/troubleshooting.html
