### ISSUE TITLE
Linting stops on line 117

### ISSUE THREAD

**Issue by ahallicks** [attenzione/SublimeLinter-scss-lint#36]
I have previously installed everything and it has worked fine. However, I noticed today that linting now doesn't get past line #117 of **any** file. Instead I get the following error:

![scss-lint](https://cloud.githubusercontent.com/assets/717299/13673103/7d4bca74-e6cf-11e5-90de-b67731eec66b.jpg)

It also doesn't show me any warnings before this line. I'm wondering at this point if it's something else I've installed but removing previously installed plugins doesn't make a difference.

**Comment by attenzione** [comment]
This error is from scss-linter, so plugin for sublime works as expected.
