### ISSUE TITLE
Doesn't show up in "Install package" search results

### ISSUE THREAD

**Issue by wouter-muller** [attenzione/SublimeLinter-scss-lint#37]
When i use Package control to install a package, and then search for "linter scss" i get no results. 

I am running Sublime Text 3 (build 3103)...

**Comment by attenzione** [comment]
Try scss lint

**Comment by wouter-muller** [comment]
<img width="489" alt="screen shot 2016-04-21 at 22 25 46" src="https://cloud.githubusercontent.com/assets/17140136/14723204/25c97302-0810-11e6-8df0-b8977c0bfebd.png">

**Comment by wouter-muller** [comment]
Even if i search for just "scss" i don't get it as one of the results... Either something is wrong on my end, or the plugin is just not accessible anymore

**Comment by attenzione** [comment]
Did you installed SublimeLinter?

On Fri, Apr 22, 2016 at 10:12 AM Wouter Muller <notifications@github.com>
wrote:

> Even if i search for just "scss" i don't get it as one of the results...
> Either something is wrong on my end, or the plugin is just not accessible
> anymore
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/attenzione/SublimeLinter-scss-lint/issues/37#issuecomment-213295890>
>
-- 

Regards, Sergey M.

**Comment by wouter-muller** [comment]
Yes, i even removed it and re-installed it, just to see if that would fix the issue, but it does not. 

I just asked a colleague of mine, he does not find it either, but he is using Sublime Text 2...

**Comment by wouter-muller** [comment]
I also tried looking for a way to download the package and then install it manually, but there is no download link anywhere.

**Comment by wouter-muller** [comment]
I do find other SublimeLinter extensions, and if i search for "linter scs" i get a few results but not the one i want...
![screen shot 2016-04-22 at 14 48 27](https://cloud.githubusercontent.com/assets/17140136/14741832/66afc748-0899-11e6-911e-9c63b6cd36aa.png)

**Comment by attenzione** [comment]
That's strange, I see package in search results.
Try to "Add Repository" directly to this github in Package Control.

**Comment by wouter-muller** [comment]
That did the trick! Thanks!

Love the extension already :)

**Comment by attenzione** [comment]
Thanks
