### ISSUE TITLE
undefined method `activate_bin_path' for Gem:Module (NoMethodError)

### ISSUE THREAD

**Issue by romanbloeth** [attenzione/SublimeLinter-scss-lint#38]
I've just uninstalled and reinstalled Ruby and Rails on my Ubuntu 14.04 LTS, but still since a few days the SublimeLinter-scss-lint doesn't work any more in ST3. The ST3 console gives me the following debugging output:

```
SublimeLinter: scss: cms_desktop.scss ['/usr/local/bin/ruby', '-S', 'scss-lint', '--config', '/var/dev/lesara.org/public_html/.scss-lint.yml'] 
SublimeLinter: scss output:
/usr/local/bin/scss-lint:22:in `<main>': undefined method `activate_bin_path' for Gem:Module (NoMethodError)
```

I have no idea whether this is a SublimeLinter, a SublimeLinter-scss-lint or any other issue, but either way I was not able to find anything related to this bug on the internet.

I have 
```
$ rails -v 
Rails 4.2.6
$ ruby -v 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

But the ruby the debugging output points to is another version:
```
/usr/local/bin/ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
```

And I can't find the place where ST configures that one...

It worked really great in the beginning, and I unfortunately do not know any more what on earth I did change on my computer before I realized that it doesn't work any more, except that I started switching from using Grunt.js to using Gulp.js.

**Comment by romanbloeth** [comment]
Ok, after adding `"~/.rbenv/shims"` to the SublimeLinter paths for Linux, I now get 'no Ruby script found in input (LoadError) ', which is Issue #26 , so I'll close this issue here.

**Comment by romanbloeth** [comment]
Ok, after I did everything mentioned in Issue #26, I'm back to my initial problem again and I am pretty clueless now.

**Comment by attenzione** [comment]
try ```scss-lint some.css``` from console

**Comment by romanbloeth** [comment]
This works fine and gives the correct output.

**Comment by attenzione** [comment]
try to run Sublime from your console

**Comment by romanbloeth** [comment]
Ok, now I get the correct output in the ST console and the error marks in the SCSS source file - only the popup listing the erorrs as I had it before is still not showing. Looks like a PATH issue?

**Comment by attenzione** [comment]
This is common problem, running sublime from console and as standalone app, somehow different paths. I have Sublime alias ```subl``` and run sublime only from console and never have path issues.

**Comment by romanbloeth** [comment]
Ok, thx for your support, @attenzione. It is not a SublimeLinter-scss-lint issue after all. I only still wonder why the errors do not pop up any more on save... Any ideas on that?

**Comment by romanbloeth** [comment]
No, all good - I just had to toggle "Show errors on save" again. Thx man!
