### ISSUE TITLE
Defining a custom config file

### ISSUE THREAD

**Issue by Camzilla** [attenzione/SublimeLinter-scss-lint#42]
I've been trying and reading everything I can regarding selecting a custom config file, but still to no avail.

My sublime text 3 logs this in the consol upon linting:
`SublimeLinter: sass: main.scss ['C:\\Users\\xxx\\AppData\\Roaming\\npm\\sass-lint.cmd', '--verbose', '--no-exit', '--format', 'stylish']`

And by using `scss-lint --config .scss-lint.yml` I thought I could point out the config file I want to use. It seems to be a lot more complicated than that, could anybody enlighten me to how you're supposed to do this right?

**Comment by jonnymaceachern** [comment]
@Camzilla, any luck with this?

Same issue here #19

**Comment by Camzilla** [comment]
Did you get this to work since you deleted your comment? I think I gave up
and removed the linter, because it slowed down sublime. Probably because it
mainly likes to checking the sort order of the properties and also what
kind of indentation I have, which no person (or program) has any business
with :)


2016-10-07 15:48 GMT+02:00 Jonny <notifications@github.com>:

**Comment by jonnymaceachern** [comment]
@Camzilla yes, but it was just a typo in my config file. I was using `scss_lint.yml` instead of `scss-lint.yml`.

**Comment by attenzione** [comment]
`scss-lint` itself try to find configuration file, read more [here](https://github.com/brigade/scss-lint#configuration)
