### ISSUE TITLE
C:\Ruby23\bin\ruby.exe: No such file or directory -- scss-lint (LoadError) 

### ISSUE THREAD

**Issue by konraddobson** [attenzione/SublimeLinter-scss-lint#46]
So scss-lint never worked on this setup. I recently learned about Sublime's debug mode and in the console, came across the following error:

SublimeLinter: scss output:
C:\Ruby23\bin\ruby.exe: No such file or directory -- scss-lint (LoadError) 
SublimeLinter: scss: _mixins.scss ['C:\\Ruby23\\bin\\ruby.exe', '-S', 'scss-lint'] 

When I looked at that path, Ruby was correctly installed in, and the ruby.exe is where it says it should be. (C:\Ruby23\bin) Sublime just can't seem to locate it or something.

Any ideas on how to fix this?

**Comment by attenzione** [comment]
it tells, that scss-lint is not found, not ruby. Did you installed scss-lint?
try to run it from terminal: 
`C:\Ruby23\bin\ruby.exe -S scss-lint`
