### ISSUE TITLE
Don´t work linters

### ISSUE THREAD

**Issue by blnpolo** [attenzione/SublimeLinter-scss-lint#56]
The Indentation "size: tab" of scss.lint.yml don't work

  Indentation:
      size: tab
      width: 4

**Comment by attenzione** [comment]
linter configuration file must be named `.scss-lint.yml`

**Comment by blnpolo** [comment]
Yes I know, all works less Indentation :(

**Comment by attenzione** [comment]
not tested, but the configuration is different for indentation (https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#indentation

works for me:
```
linters:
  Indentation:
    character: tab
    width: 4
```

**Comment by blnpolo** [comment]
Thanks!
